FROM node:10.5.0

MAINTAINER yuliang <yu.liang@freelog.com>

RUN mkdir -p /data/freelog-statistics-service

WORKDIR /data/freelog-statistics-service

COPY . /data/freelog-statistics-service

RUN npm install

ENV NODE_ENV prod
ENV EGG_SERVER_ENV prod
ENV PORT 7018
ENV TZ=Asia/Shanghai
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

EXPOSE 7018

CMD [ "npm", "start" ]
